on: [push]

name: CI

jobs:
  build_and_deploy:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
    
      - run: wasm-pack build watermark

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies
        run: npm ci
        working-directory: watermark

      - name: Build watermark app
        run: NODE_ENV=production npm run build --if-present
        working-directory: watermark

      - run: mkdir -p public/

      - run: mv ./watermark/dist ./public/watermark
      
      - run: cp plugins.json public/
      - run: ls public/

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
          keep_files: true
